package core.input.keyboard.keymap.release

import core.input.keyboard.keymap.KeyAction

interface KeyRelease {

    fun getKeyReleaseActions(): List<KeyAction>

    fun setKeyARelease(function: () -> Unit)
    fun setKeyBRelease(function: () -> Unit)
    fun setKeyCRelease(function: () -> Unit)
    fun setKeyDRelease(function: () -> Unit)
    fun setKeyERelease(function: () -> Unit)
    fun setKeyFRelease(function: () -> Unit)
    fun setKeyGRelease(function: () -> Unit)
    fun setKeyHRelease(function: () -> Unit)
    fun setKeyIRelease(function: () -> Unit)
    fun setKeyJRelease(function: () -> Unit)
    fun setKeyKRelease(function: () -> Unit)
    fun setKeyLRelease(function: () -> Unit)
    fun setKeyMRelease(function: () -> Unit)
    fun setKeyNRelease(function: () -> Unit)
    fun setKeyORelease(function: () -> Unit)
    fun setKeyPRelease(function: () -> Unit)
    fun setKeyQRelease(function: () -> Unit)
    fun setKeyRRelease(function: () -> Unit)
    fun setKeySRelease(function: () -> Unit)
    fun setKeyTRelease(function: () -> Unit)
    fun setKeyURelease(function: () -> Unit)
    fun setKeyVRelease(function: () -> Unit)
    fun setKeyWRelease(function: () -> Unit)
    fun setKeyXRelease(function: () -> Unit)
    fun setKeyYRelease(function: () -> Unit)
    fun setKeyZRelease(function: () -> Unit)

    fun setKey1Release(function: () -> Unit)
    fun setKey2Release(function: () -> Unit)
    fun setKey3Release(function: () -> Unit)
    fun setKey4Release(function: () -> Unit)
    fun setKey5Release(function: () -> Unit)
    fun setKey6Release(function: () -> Unit)
    fun setKey7Release(function: () -> Unit)
    fun setKey8Release(function: () -> Unit)
    fun setKey9Release(function: () -> Unit)
    fun setKey0Release(function: () -> Unit)

    fun setKeyEscRelease(function: () -> Unit)
    fun setKeyF1Release(function: () -> Unit)
    fun setKeyF2Release(function: () -> Unit)
    fun setKeyF3Release(function: () -> Unit)
    fun setKeyF4Release(function: () -> Unit)
    fun setKeyF5Release(function: () -> Unit)
    fun setKeyF6Release(function: () -> Unit)
    fun setKeyF7Release(function: () -> Unit)
    fun setKeyF8Release(function: () -> Unit)
    fun setKeyF9Release(function: () -> Unit)
    fun setKeyF10Release(function: () -> Unit)
    fun setKeyF11Release(function: () -> Unit)
    fun setKeyF12Release(function: () -> Unit)

    fun setKeyBackslashRelease(function: () -> Unit)
    fun setKeyApostropheRelease(function: () -> Unit)
    fun setKeyRightAltRelease(function: () -> Unit)
    fun setKeyLeftAltRelease(function: () -> Unit)
    fun setKeyGraveAccentRelease(function: () -> Unit)
    fun setKeyBackspaceRelease(function: () -> Unit)
    fun setKeyLeftBracketRelease(function: () -> Unit)
    fun setKeyRightBracketRelease(function: () -> Unit)
    fun setKeyCapsLockRelease(function: () -> Unit)
    fun setKeyCommaRelease(function: () -> Unit)
    fun setKeyLeftControlRelease(function: () -> Unit)
    fun setKeyRightControlRelease(function: () -> Unit)
    fun setKeyDeleteRelease(function: () -> Unit)
    fun setKeyEnterRelease(function: () -> Unit)
    fun setKeyEqualRelease(function: () -> Unit)
    fun setKeyInsertRelease(function: () -> Unit)
    fun setKeyLastRelease(function: () -> Unit)
    fun setKeyLeftShiftRelease(function: () -> Unit)
    fun setKeyRightShiftRelease(function: () -> Unit)
    fun setKeyLeftSuperRelease(function: () -> Unit)
    fun setKeyRightSuperRelease(function: () -> Unit)
    fun setKeyNumLockRelease(function: () -> Unit)
    fun setKeyScrollLockRelease(function: () -> Unit)
    fun setKeyMenuRelease(function: () -> Unit)
    fun setKeyMultiplyRelease(function: () -> Unit)
    fun setKeyMinusRelease(function: () -> Unit)
    fun setKeyPauseRelease(function: () -> Unit)
    fun setKeyPrintScreenRelease(function: () -> Unit)
    fun setKeyPeriodRelease(function: () -> Unit)
    fun setKeySemicolonRelease(function: () -> Unit)
    fun setKeySlashRelease(function: () -> Unit)
    fun setKeySpaceRelease(function: () -> Unit)
    fun setKeyTabRelease(function: () -> Unit)
    fun setKeyUnknownRelease(function: () -> Unit)

    fun setKeyNumeric1Release(function: () -> Unit)
    fun setKeyNumeric2Release(function: () -> Unit)
    fun setKeyNumeric3Release(function: () -> Unit)
    fun setKeyNumeric4Release(function: () -> Unit)
    fun setKeyNumeric5Release(function: () -> Unit)
    fun setKeyNumeric6Release(function: () -> Unit)
    fun setKeyNumeric7Release(function: () -> Unit)
    fun setKeyNumeric8Release(function: () -> Unit)
    fun setKeyNumeric9Release(function: () -> Unit)
    fun setKeyNumericAddRelease(function: () -> Unit)
    fun setKeyNumericSubtractRelease(function: () -> Unit)
    fun setKeyNumericMultiplyRelease(function: () -> Unit)
    fun setKeyNumericDivideRelease(function: () -> Unit)
    fun setKeyNumericEnterRelease(function: () -> Unit)
    fun setKeyNumericEqualRelease(function: () -> Unit)
    fun setKeyNumericDecimalRelease(function: () -> Unit)

    fun setKeyPageDownRelease(function: () -> Unit)
    fun setKeyPageUpRelease(function: () -> Unit)
    fun setKeyHomeRelease(function: () -> Unit)
    fun setKeyEndRelease(function: () -> Unit)

    fun setKeyUpRelease(function: () -> Unit)
    fun setKeyDownRelease(function: () -> Unit)
    fun setKeyLeftRelease(function: () -> Unit)
    fun setKeyRightRelease(function: () -> Unit)
}