package core.input.keyboard.keymap.justpressed

import core.input.keyboard.keymap.KeyAction

interface KeyJustPressed {

    fun getKeyJustPressedActions(): List<KeyAction>

    fun setKeyAJustPressed(function: () -> Unit)
    fun setKeyBJustPressed(function: () -> Unit)
    fun setKeyCJustPressed(function: () -> Unit)
    fun setKeyDJustPressed(function: () -> Unit)
    fun setKeyEJustPressed(function: () -> Unit)
    fun setKeyFJustPressed(function: () -> Unit)
    fun setKeyGJustPressed(function: () -> Unit)
    fun setKeyHJustPressed(function: () -> Unit)
    fun setKeyIJustPressed(function: () -> Unit)
    fun setKeyJJustPressed(function: () -> Unit)
    fun setKeyKJustPressed(function: () -> Unit)
    fun setKeyLJustPressed(function: () -> Unit)
    fun setKeyMJustPressed(function: () -> Unit)
    fun setKeyNJustPressed(function: () -> Unit)
    fun setKeyOJustPressed(function: () -> Unit)
    fun setKeyPJustPressed(function: () -> Unit)
    fun setKeyQJustPressed(function: () -> Unit)
    fun setKeyRJustPressed(function: () -> Unit)
    fun setKeySJustPressed(function: () -> Unit)
    fun setKeyTJustPressed(function: () -> Unit)
    fun setKeyUJustPressed(function: () -> Unit)
    fun setKeyVJustPressed(function: () -> Unit)
    fun setKeyWJustPressed(function: () -> Unit)
    fun setKeyXJustPressed(function: () -> Unit)
    fun setKeyYJustPressed(function: () -> Unit)
    fun setKeyZJustPressed(function: () -> Unit)

    fun setKey1JustPressed(function: () -> Unit)
    fun setKey2JustPressed(function: () -> Unit)
    fun setKey3JustPressed(function: () -> Unit)
    fun setKey4JustPressed(function: () -> Unit)
    fun setKey5JustPressed(function: () -> Unit)
    fun setKey6JustPressed(function: () -> Unit)
    fun setKey7JustPressed(function: () -> Unit)
    fun setKey8JustPressed(function: () -> Unit)
    fun setKey9JustPressed(function: () -> Unit)
    fun setKey0JustPressed(function: () -> Unit)

    fun setKeyEscJustPressed(function: () -> Unit)
    fun setKeyF1JustPressed(function: () -> Unit)
    fun setKeyF2JustPressed(function: () -> Unit)
    fun setKeyF3JustPressed(function: () -> Unit)
    fun setKeyF4JustPressed(function: () -> Unit)
    fun setKeyF5JustPressed(function: () -> Unit)
    fun setKeyF6JustPressed(function: () -> Unit)
    fun setKeyF7JustPressed(function: () -> Unit)
    fun setKeyF8JustPressed(function: () -> Unit)
    fun setKeyF9JustPressed(function: () -> Unit)
    fun setKeyF10JustPressed(function: () -> Unit)
    fun setKeyF11JustPressed(function: () -> Unit)
    fun setKeyF12JustPressed(function: () -> Unit)

    fun setKeyBackslashJustPressed(function: () -> Unit)
    fun setKeyApostropheJustPressed(function: () -> Unit)
    fun setKeyRightAltJustPressed(function: () -> Unit)
    fun setKeyLeftAltJustPressed(function: () -> Unit)
    fun setKeyGraveAccentJustPressed(function: () -> Unit)
    fun setKeyBackspaceJustPressed(function: () -> Unit)
    fun setKeyLeftBracketJustPressed(function: () -> Unit)
    fun setKeyRightBracketJustPressed(function: () -> Unit)
    fun setKeyCapsLockJustPressed(function: () -> Unit)
    fun setKeyCommaJustPressed(function: () -> Unit)
    fun setKeyLeftControlJustPressed(function: () -> Unit)
    fun setKeyRightControlJustPressed(function: () -> Unit)
    fun setKeyDeleteJustPressed(function: () -> Unit)
    fun setKeyEnterJustPressed(function: () -> Unit)
    fun setKeyEqualJustPressed(function: () -> Unit)
    fun setKeyInsertJustPressed(function: () -> Unit)
    fun setKeyLastJustPressed(function: () -> Unit)
    fun setKeyLeftShiftJustPressed(function: () -> Unit)
    fun setKeyRightShiftJustPressed(function: () -> Unit)
    fun setKeyLeftSuperJustPressed(function: () -> Unit)
    fun setKeyRightSuperJustPressed(function: () -> Unit)
    fun setKeyNumLockJustPressed(function: () -> Unit)
    fun setKeyScrollLockJustPressed(function: () -> Unit)
    fun setKeyMenuJustPressed(function: () -> Unit)
    fun setKeyMultiplyJustPressed(function: () -> Unit)
    fun setKeyMinusJustPressed(function: () -> Unit)
    fun setKeyPauseJustPressed(function: () -> Unit)
    fun setKeyPrintScreenJustPressed(function: () -> Unit)
    fun setKeyPeriodJustPressed(function: () -> Unit)
    fun setKeySemicolonJustPressed(function: () -> Unit)
    fun setKeySlashJustPressed(function: () -> Unit)
    fun setKeySpaceJustPressed(function: () -> Unit)
    fun setKeyTabJustPressed(function: () -> Unit)
    fun setKeyUnknownJustPressed(function: () -> Unit)

    fun setKeyNumeric1JustPressed(function: () -> Unit)
    fun setKeyNumeric2JustPressed(function: () -> Unit)
    fun setKeyNumeric3JustPressed(function: () -> Unit)
    fun setKeyNumeric4JustPressed(function: () -> Unit)
    fun setKeyNumeric5JustPressed(function: () -> Unit)
    fun setKeyNumeric6JustPressed(function: () -> Unit)
    fun setKeyNumeric7JustPressed(function: () -> Unit)
    fun setKeyNumeric8JustPressed(function: () -> Unit)
    fun setKeyNumeric9JustPressed(function: () -> Unit)
    fun setKeyNumericAddJustPressed(function: () -> Unit)
    fun setKeyNumericSubtractJustPressed(function: () -> Unit)
    fun setKeyNumericMultiplyJustPressed(function: () -> Unit)
    fun setKeyNumericDivideJustPressed(function: () -> Unit)
    fun setKeyNumericEnterJustPressed(function: () -> Unit)
    fun setKeyNumericEqualJustPressed(function: () -> Unit)
    fun setKeyNumericDecimalJustPressed(function: () -> Unit)

    fun setKeyPageDownJustPressed(function: () -> Unit)
    fun setKeyPageUpJustPressed(function: () -> Unit)
    fun setKeyHomeJustPressed(function: () -> Unit)
    fun setKeyEndJustPressed(function: () -> Unit)

    fun setKeyUpJustPressed(function: () -> Unit)
    fun setKeyDownJustPressed(function: () -> Unit)
    fun setKeyLeftJustPressed(function: () -> Unit)
    fun setKeyRightJustPressed(function: () -> Unit)
}