package kgames.core.input.keyboard.keymap.pressed

import kgames.core.input.Action

interface KeyPressed {

    fun getKeyPressedActions(): List<Action>

    fun setKeyAPressed(function: () -> Unit)
    fun setKeyBPressed(function: () -> Unit)
    fun setKeyCPressed(function: () -> Unit)
    fun setKeyDPressed(function: () -> Unit)
    fun setKeyEPressed(function: () -> Unit)
    fun setKeyFPressed(function: () -> Unit)
    fun setKeyGPressed(function: () -> Unit)
    fun setKeyHPressed(function: () -> Unit)
    fun setKeyIPressed(function: () -> Unit)
    fun setKeyJPressed(function: () -> Unit)
    fun setKeyKPressed(function: () -> Unit)
    fun setKeyLPressed(function: () -> Unit)
    fun setKeyMPressed(function: () -> Unit)
    fun setKeyNPressed(function: () -> Unit)
    fun setKeyOPressed(function: () -> Unit)
    fun setKeyPPressed(function: () -> Unit)
    fun setKeyQPressed(function: () -> Unit)
    fun setKeyRPressed(function: () -> Unit)
    fun setKeySPressed(function: () -> Unit)
    fun setKeyTPressed(function: () -> Unit)
    fun setKeyUPressed(function: () -> Unit)
    fun setKeyVPressed(function: () -> Unit)
    fun setKeyWPressed(function: () -> Unit)
    fun setKeyXPressed(function: () -> Unit)
    fun setKeyYPressed(function: () -> Unit)
    fun setKeyZPressed(function: () -> Unit)

    fun setKey1Pressed(function: () -> Unit)
    fun setKey2Pressed(function: () -> Unit)
    fun setKey3Pressed(function: () -> Unit)
    fun setKey4Pressed(function: () -> Unit)
    fun setKey5Pressed(function: () -> Unit)
    fun setKey6Pressed(function: () -> Unit)
    fun setKey7Pressed(function: () -> Unit)
    fun setKey8Pressed(function: () -> Unit)
    fun setKey9Pressed(function: () -> Unit)
    fun setKey0Pressed(function: () -> Unit)

    fun setKeyEscPressed(function: () -> Unit)
    fun setKeyF1Pressed(function: () -> Unit)
    fun setKeyF2Pressed(function: () -> Unit)
    fun setKeyF3Pressed(function: () -> Unit)
    fun setKeyF4Pressed(function: () -> Unit)
    fun setKeyF5Pressed(function: () -> Unit)
    fun setKeyF6Pressed(function: () -> Unit)
    fun setKeyF7Pressed(function: () -> Unit)
    fun setKeyF8Pressed(function: () -> Unit)
    fun setKeyF9Pressed(function: () -> Unit)
    fun setKeyF10Pressed(function: () -> Unit)
    fun setKeyF11Pressed(function: () -> Unit)
    fun setKeyF12Pressed(function: () -> Unit)

    fun setKeyBackslashPressed(function: () -> Unit)
    fun setKeyApostrophePressed(function: () -> Unit)
    fun setKeyRightAltPressed(function: () -> Unit)
    fun setKeyLeftAltPressed(function: () -> Unit)
    fun setKeyGraveAccentPressed(function: () -> Unit)
    fun setKeyBackspacePressed(function: () -> Unit)
    fun setKeyLeftBracketPressed(function: () -> Unit)
    fun setKeyRightBracketPressed(function: () -> Unit)
    fun setKeyCapsLockPressed(function: () -> Unit)
    fun setKeyCommaPressed(function: () -> Unit)
    fun setKeyLeftControlPressed(function: () -> Unit)
    fun setKeyRightControlPressed(function: () -> Unit)
    fun setKeyDeletePressed(function: () -> Unit)
    fun setKeyEnterPressed(function: () -> Unit)
    fun setKeyEqualPressed(function: () -> Unit)
    fun setKeyInsertPressed(function: () -> Unit)
    fun setKeyLastPressed(function: () -> Unit)
    fun setKeyLeftShiftPressed(function: () -> Unit)
    fun setKeyRightShiftPressed(function: () -> Unit)
    fun setKeyLeftSuperPressed(function: () -> Unit)
    fun setKeyRightSuperPressed(function: () -> Unit)
    fun setKeyNumLockPressed(function: () -> Unit)
    fun setKeyScrollLockPressed(function: () -> Unit)
    fun setKeyMenuPressed(function: () -> Unit)
    fun setKeyMultiplyPressed(function: () -> Unit)
    fun setKeyMinusPressed(function: () -> Unit)
    fun setKeyPausePressed(function: () -> Unit)
    fun setKeyPrintScreenPressed(function: () -> Unit)
    fun setKeyPeriodPressed(function: () -> Unit)
    fun setKeySemicolonPressed(function: () -> Unit)
    fun setKeySlashPressed(function: () -> Unit)
    fun setKeySpacePressed(function: () -> Unit)
    fun setKeyTabPressed(function: () -> Unit)
    fun setKeyUnknownPressed(function: () -> Unit)

    fun setKeyNumeric1Pressed(function: () -> Unit)
    fun setKeyNumeric2Pressed(function: () -> Unit)
    fun setKeyNumeric3Pressed(function: () -> Unit)
    fun setKeyNumeric4Pressed(function: () -> Unit)
    fun setKeyNumeric5Pressed(function: () -> Unit)
    fun setKeyNumeric6Pressed(function: () -> Unit)
    fun setKeyNumeric7Pressed(function: () -> Unit)
    fun setKeyNumeric8Pressed(function: () -> Unit)
    fun setKeyNumeric9Pressed(function: () -> Unit)
    fun setKeyNumericAddPressed(function: () -> Unit)
    fun setKeyNumericSubtractPressed(function: () -> Unit)
    fun setKeyNumericMultiplyPressed(function: () -> Unit)
    fun setKeyNumericDividePressed(function: () -> Unit)
    fun setKeyNumericEnterPressed(function: () -> Unit)
    fun setKeyNumericEqualPressed(function: () -> Unit)
    fun setKeyNumericDecimalPressed(function: () -> Unit)

    fun setKeyPageDownPressed(function: () -> Unit)
    fun setKeyPageUpPressed(function: () -> Unit)
    fun setKeyHomePressed(function: () -> Unit)
    fun setKeyEndPressed(function: () -> Unit)

    fun setKeyUpPressed(function: () -> Unit)
    fun setKeyDownPressed(function: () -> Unit)
    fun setKeyLeftPressed(function: () -> Unit)
    fun setKeyRightPressed(function: () -> Unit)

}