package core.input.keyboard.keymap.held

import core.input.keyboard.keymap.KeyAction

interface KeyHeld {

    fun getKeyHeldActions(): List<KeyAction>

    fun setKeyAHeld(function: () -> Unit)
    fun setKeyBHeld(function: () -> Unit)
    fun setKeyCHeld(function: () -> Unit)
    fun setKeyDHeld(function: () -> Unit)
    fun setKeyEHeld(function: () -> Unit)
    fun setKeyFHeld(function: () -> Unit)
    fun setKeyGHeld(function: () -> Unit)
    fun setKeyHHeld(function: () -> Unit)
    fun setKeyIHeld(function: () -> Unit)
    fun setKeyJHeld(function: () -> Unit)
    fun setKeyKHeld(function: () -> Unit)
    fun setKeyLHeld(function: () -> Unit)
    fun setKeyMHeld(function: () -> Unit)
    fun setKeyNHeld(function: () -> Unit)
    fun setKeyOHeld(function: () -> Unit)
    fun setKeyPHeld(function: () -> Unit)
    fun setKeyQHeld(function: () -> Unit)
    fun setKeyRHeld(function: () -> Unit)
    fun setKeySHeld(function: () -> Unit)
    fun setKeyTHeld(function: () -> Unit)
    fun setKeyUHeld(function: () -> Unit)
    fun setKeyVHeld(function: () -> Unit)
    fun setKeyWHeld(function: () -> Unit)
    fun setKeyXHeld(function: () -> Unit)
    fun setKeyYHeld(function: () -> Unit)
    fun setKeyZHeld(function: () -> Unit)

    fun setKey1Held(function: () -> Unit)
    fun setKey2Held(function: () -> Unit)
    fun setKey3Held(function: () -> Unit)
    fun setKey4Held(function: () -> Unit)
    fun setKey5Held(function: () -> Unit)
    fun setKey6Held(function: () -> Unit)
    fun setKey7Held(function: () -> Unit)
    fun setKey8Held(function: () -> Unit)
    fun setKey9Held(function: () -> Unit)
    fun setKey0Held(function: () -> Unit)

    fun setKeyEscHeld(function: () -> Unit)
    fun setKeyF1Held(function: () -> Unit)
    fun setKeyF2Held(function: () -> Unit)
    fun setKeyF3Held(function: () -> Unit)
    fun setKeyF4Held(function: () -> Unit)
    fun setKeyF5Held(function: () -> Unit)
    fun setKeyF6Held(function: () -> Unit)
    fun setKeyF7Held(function: () -> Unit)
    fun setKeyF8Held(function: () -> Unit)
    fun setKeyF9Held(function: () -> Unit)
    fun setKeyF10Held(function: () -> Unit)
    fun setKeyF11Held(function: () -> Unit)
    fun setKeyF12Held(function: () -> Unit)

    fun setKeyBackslashHeld(function: () -> Unit)
    fun setKeyApostropheHeld(function: () -> Unit)
    fun setKeyRightAltHeld(function: () -> Unit)
    fun setKeyLeftAltHeld(function: () -> Unit)
    fun setKeyGraveAccentHeld(function: () -> Unit)
    fun setKeyBackspaceHeld(function: () -> Unit)
    fun setKeyLeftBracketHeld(function: () -> Unit)
    fun setKeyRightBracketHeld(function: () -> Unit)
    fun setKeyCapsLockHeld(function: () -> Unit)
    fun setKeyCommaHeld(function: () -> Unit)
    fun setKeyLeftControlHeld(function: () -> Unit)
    fun setKeyRightControlHeld(function: () -> Unit)
    fun setKeyDeleteHeld(function: () -> Unit)
    fun setKeyEnterHeld(function: () -> Unit)
    fun setKeyEqualHeld(function: () -> Unit)
    fun setKeyInsertHeld(function: () -> Unit)
    fun setKeyLastHeld(function: () -> Unit)
    fun setKeyLeftShiftHeld(function: () -> Unit)
    fun setKeyRightShiftHeld(function: () -> Unit)
    fun setKeyLeftSuperHeld(function: () -> Unit)
    fun setKeyRightSuperHeld(function: () -> Unit)
    fun setKeyNumLockHeld(function: () -> Unit)
    fun setKeyScrollLockHeld(function: () -> Unit)
    fun setKeyMenuHeld(function: () -> Unit)
    fun setKeyMultiplyHeld(function: () -> Unit)
    fun setKeyMinusHeld(function: () -> Unit)
    fun setKeyPauseHeld(function: () -> Unit)
    fun setKeyPrintScreenHeld(function: () -> Unit)
    fun setKeyPeriodHeld(function: () -> Unit)
    fun setKeySemicolonHeld(function: () -> Unit)
    fun setKeySlashHeld(function: () -> Unit)
    fun setKeySpaceHeld(function: () -> Unit)
    fun setKeyTabHeld(function: () -> Unit)
    fun setKeyUnknownHeld(function: () -> Unit)

    fun setKeyNumeric1Held(function: () -> Unit)
    fun setKeyNumeric2Held(function: () -> Unit)
    fun setKeyNumeric3Held(function: () -> Unit)
    fun setKeyNumeric4Held(function: () -> Unit)
    fun setKeyNumeric5Held(function: () -> Unit)
    fun setKeyNumeric6Held(function: () -> Unit)
    fun setKeyNumeric7Held(function: () -> Unit)
    fun setKeyNumeric8Held(function: () -> Unit)
    fun setKeyNumeric9Held(function: () -> Unit)
    fun setKeyNumericAddHeld(function: () -> Unit)
    fun setKeyNumericSubtractHeld(function: () -> Unit)
    fun setKeyNumericMultiplyHeld(function: () -> Unit)
    fun setKeyNumericDivideHeld(function: () -> Unit)
    fun setKeyNumericEnterHeld(function: () -> Unit)
    fun setKeyNumericEqualHeld(function: () -> Unit)
    fun setKeyNumericDecimalHeld(function: () -> Unit)

    fun setKeyPageDownHeld(function: () -> Unit)
    fun setKeyPageUpHeld(function: () -> Unit)
    fun setKeyHomeHeld(function: () -> Unit)
    fun setKeyEndHeld(function: () -> Unit)

    fun setKeyUpHeld(function: () -> Unit)
    fun setKeyDownHeld(function: () -> Unit)
    fun setKeyLeftHeld(function: () -> Unit)
    fun setKeyRightHeld(function: () -> Unit)

}